site_name: Flying Bear Klipper
site_url: https://Wolf65.github.io/FBRebornKlipper/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
#   - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    scheme: slate   
    primary: teal
    accent: purple 

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Wolf65/FBRebornKlipper
    - icon: fontawesome/brands/telegram
      link: https://t.me/IronWolf65

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Wolf65/FBRebornKlipper"  target="_blank" rel="noopener">Iron Wolf</a>