site_name: Flying Bear Klipper
site_url: https://wolf65.github.io/FBRebornKlipper/
repo_name: Wolf65/FBRebornKlipper
repo_url: https://github.com/Wolf65/FBRebornKlipper

theme:
  language: ru
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
#    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    
  palette:
    scheme: slate   
    primary: teal
    accent: purple 

plugins:
    - search
    - awesome-pages
    - git-revision-date-localized:
        locale: ru
        timezone: Europe/Moscow
        type: datetime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Wolf65/FBRebornKlipper
    - icon: fontawesome/brands/telegram
      link: https://t.me/IronWolf65

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - md_in_html       

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/Wolf65/FBRebornKlipper"  target="_blank" rel="noopener">Iron Wolf</a>